version: '3'

services:
  server:
    container_name: server
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.2

  mail:
    container_name: mail
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.3

  client:
    container_name: client
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.4

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
