FROM ubuntu:18.04
RUN apt update
RUN apt install bind9 -y
RUN apt install net-tools -y
RUN apt install dnsutils -y
RUN apt install vim -y
RUN apt install mailutils -y
RUN apt instal postfix -y
CMD tail -f /dev/null
