version: '3'

services:
  dns_server:
    container_name: dns_server
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.2

  dns_mail:
    container_name: dns_mail
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.3

  dns_client:
    container_name: dns_client
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.4

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
