version: '3'

services:
  machine1:
    container_name: machine1
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.2

  machine2:
    container_name: machine2
    build:
      context: .
    networks:
      mynetwork:
        ipv4_address: 192.168.10.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
