version: '3'

services:
  web_server:
    container_name: web_server
    build:
      context: .
    ports: 
      - 80:80
    networks:
      paulocovid:
        ipv4_address: 192.168.11.2

  web_client:
    container_name: web_client
    build:
      context: .
    ports:
      - 8080:80
    networks:
      paulocovid:
        ipv4_address: 192.168.11.3

networks:
  paulocovid:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.0/24
